name: Run Automation Exercise Tests

on:
  workflow_dispatch:

jobs:
  run-automation-exercise:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Automation Exercise Tests
        run: |
          npx playwright test tests/e2e/Automation\ Excercise/checkout.spec.ts \
                              tests/e2e/Automation\ Excercise/login-registration.spec.ts \
                              tests/e2e/Automation\ Excercise/product-search.spec.ts \
                              tests/e2e/Automation\ Excercise/shopping-cart.spec.ts
