name: Run Sauce Demo Tests (Headed)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  headed-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers with Dependencies
        run: npx playwright install --with-deps

      - name: Run Sauce Demo Tests (headed mode using xvfb)
        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npx playwright test tests/e2e/sauce-demo/
